#theme: jekyll-theme-hacker
theme: jekyll-theme-minimal
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme:  pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 

title: [e1nself!1!11!!]
description: [random ramblings about IT-security and other stuff]

show_downloads: false
