#theme: jekyll-theme-hacker
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: [e1nself!11!1!!]
description: [Somewhere in the dark corners of the interwebz...]

show_downloads: false
